Implement chain publisher
CaoThien96/chain-publisher pull request #3
Opened 2022-02-17 02:30 UTC by CaoThien96

2022-02-17 04:13 UTC, Zergity requested changes

2022-02-17 04:13 UTC, Zergity commented on test/quick-start/SfarmExample.js
> +                changes: {}
why do we need to store `changes` here?

2022-02-17 04:13 UTC, Zergity commented on test/quick-start/SfarmExample.js
> +        safeDepth: 64,
try the sample with different `safeDepth` for each consumer

2022-02-17 04:13 UTC, Zergity commented on test/quick-start/SfarmExample.js
> +        order: 1
please remove the order logic, and call the subscriber.appLogs consequently

2022-02-17 04:13 UTC, Zergity commented on lib/chain-publisher.js
> +        let nextPastProcess = Date.now()
`nextPastProcess` is unused

2022-02-17 04:22 UTC, CaoThien96 commented on test/quick-start/SfarmExample.js
> +                changes: {}
I do not understand. `changes` is value that the client saves after processing the logs

2022-02-18 01:15 UTC, CaoThien96 commented on lib/chain-publisher.js
> +        let nextPastProcess = Date.now()
`nextPastProcess` Used in next loop when `this.context.lastProcessed == this.context.head`, will wait 3 seconds. The intent is that every time the processor repeats with a different head

2022-02-18 01:58 UTC, CaoThien96 commented on lib/chain-publisher.js
> +                    .sort((a, b) => (a.blockNumber - b.blockNumber) || (a.logIndex - b.logIndex))
resolved

2022-02-18 01:58 UTC, CaoThien96 commented on test/quick-start/SfarmExample.js
> +                changes: {}
resolved

2022-02-18 01:58 UTC, CaoThien96 commented on test/quick-start/SfarmExample.js
> +        safeDepth: 64,
resolved

2022-02-18 01:58 UTC, CaoThien96 commented on test/quick-start/SfarmExample.js
> +        order: 1
resolved

2022-02-21 04:40 UTC, Zergity commented on doc/quick-start.md
> +* File [WalletSample.js](../test/quick-start/WalletSample.js)
why test files is located in a `quick-start` folder?

2022-02-23 01:33 UTC, CaoThien96 commented on doc/quick-start.md
> +* File [WalletSample.js](../test/quick-start/WalletSample.js)
I misunderstood the purpose of quick start. 
It should be SfarmExample.js which would be more correct

2022-02-23 01:53 UTC, Zergity commented on doc/quick-start.md
> +* File [WalletSample.js](../test/quick-start/WalletSample.js)
I mean the SfarmExample.js, why is it INSIDE the folder `test/quick-start`?

2022-03-07 07:05 UTC, Zergity requested changes
please change the apllyLogs interface to: `function applyLogs(storage, logs)` and handle the `storage.setItem` and `removeItem` in the lib

2022-04-25 04:08 UTC, Zergity approved these changes

2022-04-25 04:08 UTC, merged